name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - 27-help-understand-engine
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          sudo apt-get install -y doxygen doxygen-doc doxygen-gui graphviz
          doxygen docs/doxygen.conf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs